- project:
    templates:
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
    post:
      jobs:
        - publish-openstack-python-branch-tarball
